replicaCount: 2

image:
  repository: node-todo-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: my-node-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}
